### ISSUE TITLE
when use master branch code compile proxy, client connect proxy cause "Connection refused".

### ISSUE THREAD

**Issue by dongzl** [database-mesh/pisanix#130]
### What version of Pisanix are you using?

newest master code.

### What did happened?
Server:
```
Jun 27 10:05:26.206 ERROR runtime_mysql::server::server: err:Error { kind: Protocol(Io(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })) }
thread 'pisa-proxy' panicked at 'called `Option::unwrap()` on a `None` value', runtime/mysql/src/transaction_fsm.rs:314:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jun 27 10:05:43.582  INFO proxy::listener: pisa-proxy client_ip: 127.0.0.1 - backend_type: "mysql"
Jun 27 10:05:43.667 ERROR runtime_mysql::server::server: err:Error { kind: Protocol(Io(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })) }
thread 'pisa-proxy' panicked at 'called `Option::unwrap()` on a `None` value', runtime/mysql/src/transaction_fsm.rs:314:43
```

Client:
```
mysql> show databases;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    2
Current database: *** NONE ***

ERROR 2013 (HY000): Lost connection to MySQL server during query
mysql>
```

**Comment by wbtlb** [comment]
Please provide your configuration and the command of starting. @dongzl

**Comment by dongzl** [comment]
```
# api 配置块，对应命令行参数和环境变量
[admin]
# api 端口
port = "8081"
# 日志级别
log_level = "INFO"

# pisa-proxy 代理配置块
[proxy]
# config a proxy
[[proxy.config]]
# proxy 代理地址
listen_addr = "0.0.0.0:9088"
# proxy 认证用户名
user = "root"
# proxy 认证密码
password = "12345678"
# proxy schema
db = "test"
# 配置后端数据源类型
backend_type = "mysql"
# proxy 与后端数据库建连连接池大小，值范围：1 ~ 255, 默认值：64
pool_size = 3

# 后端负载均衡配置
[proxy.config.simple_loadbalance]
# 负载均衡算法：[random/roundrobin], 默认值: random 算法
balance_type = "random"
# 选择挂载后端节点
nodes = ["ds001"]

[[proxy.config.plugin.concurrency_control]]
regex = "aaa"
max_concurrency = 5
duration = 333

[[proxy.config.plugin.concurrency_control]]
regex = "bbb"
max_concurrency = 5
duration = 333

[[proxy.config.plugin.circuit_break]]
regex = "111"

[[proxy.config.plugin.circuit_break]]
regex = "222"

# 后端数据源配置
[mysql]
[[mysql.node]]
# 数据源 name
name = "ds001"
# database name
db = "employees"
# 数据库 user
user = "root"
# 数据库 password
password = "123456"
# 数据库地址
host = "127.0.0.1"
# 数据库端口
port = 3307
# 负载均衡节点权重
weight = 1
```

**Comment by dongzl** [comment]
Start proxy server command:

```
LOCAL_CONFIG=true target/debug/proxy -c examples/example-config.toml
```

**Comment by dongzl** [comment]
when start pisa-proxy, the config path is error, so start success, but client connect refused.

**Comment by wbtlb** [comment]
We will optimize in the future.Thanks for your report. @dongzl
